### PR TITLE
Fix for Ubuntu-18 wallet

### PR DESCRIPTION
**Pull request by mati3**
Hello, here you have a solution for Ubuntu-18, I commented in file readme-qt.rst in the repository that I cloned. Only I compiled with the named libraries. Could you please create a new release with this fix?

### CODE REVIEW

**Comment by erseco** [comment]
Thanks, @mati3, maybe we can add the needed code to generate a .deb package, makes sense?

**Comment by turcol** [comment]
@mati3 thank you for your PR. Could you please update it to just replace the following lines under Debian? These lines will apply to Debian / Ubuntu 18.04.

```    apt-get install qt5-default qt5-qmake qtbase5-dev-tools qttools5-dev-tools \```
```        build-essential libboost-all-dev libssl1.0-dev libdb++-dev libminiupnpc-dev  -y```

The packages we install now under Debian includes ```libssl-dev``` which takes the default OpenSSL library for the release being run. For Ubuntu 16.04 the OpenSSL used by default is version 1.0, while for Ubuntu 18.04 is version 1.1. There are some imcompatibilities between version 1.0 and 1.1 and the code won't compile under version 1.1.

Your suggestion to include ```libssl1.0-dev``` resolve that issue.

Thanks @mati3 and @erseco for your support

**Comment by mati3** [comment]
@turcol, the code is already updated, please check it out and thanks for everything.

**Comment by turcol** [comment]
Thanks @mati3 !!

**Pull request merged**
